Traceback (most recent call last):
  File "/usr/local/Cellar/letsencrypt/0.4.0/libexec/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.0', 'console_scripts', 'letsencrypt')()
  File "/usr/local/Cellar/letsencrypt/0.4.0/libexec/lib/python2.7/site-packages/letsencrypt/cli.py", line 1950, in main
    setup_logging(config, _cli_log_handler, logfile='letsencrypt.log')
  File "/usr/local/Cellar/letsencrypt/0.4.0/libexec/lib/python2.7/site-packages/letsencrypt/cli.py", line 1863, in setup_logging
    config, logfile=logfile, fmt=fmt)
  File "/usr/local/Cellar/letsencrypt/0.4.0/libexec/lib/python2.7/site-packages/letsencrypt/cli.py", line 1834, in setup_log_file_handler
    log_file_path, maxBytes=2 ** 20, backupCount=10)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
